/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2017-03-06 13:37:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("<link href=\"./css/font-awesome.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("<link href=\"./css/main.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<header class=\"navbar navbar-inverse navbar-fixed-top\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"dashboard.html\"> Hello ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\t\t\twelcome in : Application - Computer Database</a>\n");
      out.write("\t</div>\n");
      out.write("\t</header>\n");
      out.write("\n");
      out.write("\t<section id=\"main\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<h1 id=\"homeTitle\">121 Computers found</h1>\n");
      out.write("\t\t<div id=\"actions\" class=\"form-horizontal\">\n");
      out.write("\t\t\t<div class=\"pull-left\">\n");
      out.write("\t\t\t\t<form id=\"searchForm\" action=\"#\" method=\"GET\" class=\"form-inline\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<input type=\"search\" id=\"searchbox\" name=\"search\"\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" placeholder=\"Search name\" /> <input\n");
      out.write("\t\t\t\t\t\ttype=\"submit\" id=\"searchsubmit\" value=\"Filter by name\"\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-primary\" />\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t<a class=\"btn btn-success\" id=\"addComputer\" href=\"addComputer.html\">Add\n");
      out.write("\t\t\t\t\tComputer</a> <a class=\"btn btn-default\" id=\"editComputer\" href=\"#\"\n");
      out.write("\t\t\t\t\tonclick=\"$.fn.toggleEditMode();\">Edit</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<form id=\"deleteForm\" action=\"#\" method=\"POST\">\n");
      out.write("\t\t<input type=\"hidden\" name=\"selection\" value=\"\">\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("\t<div class=\"container\" style=\"margin-top: 10px;\">\n");
      out.write("\t\t<table class=\"table table-striped table-bordered\">\n");
      out.write("\t\t\t<thead>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<!-- Variable declarations for passing labels as parameters -->\n");
      out.write("\t\t\t\t\t<!-- Table header for Computer Name -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<th class=\"editMode\" style=\"width: 60px; height: 22px;\"><input\n");
      out.write("\t\t\t\t\t\ttype=\"checkbox\" id=\"selectall\" /> <span\n");
      out.write("\t\t\t\t\t\tstyle=\"vertical-align: top;\"> - <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\tid=\"deleteSelected\" onclick=\"$.fn.deleteSelected();\"> <i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-trash-o fa-lg\"></i>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</span></th>\n");
      out.write("\t\t\t\t\t<th>Computer name</th>\n");
      out.write("\t\t\t\t\t<th>Introduced date</th>\n");
      out.write("\t\t\t\t\t<!-- Table header for Discontinued Date -->\n");
      out.write("\t\t\t\t\t<th>Discontinued date</th>\n");
      out.write("\t\t\t\t\t<!-- Table header for Company -->\n");
      out.write("\t\t\t\t\t<th>Company</th>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</thead>\n");
      out.write("\t\t\t<!-- Browse attribute computers -->\n");
      out.write("\t\t\t<tbody id=\"results\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"editMode\"><input type=\"checkbox\" name=\"cb\"\n");
      out.write("\t\t\t\t\t\tclass=\"cb\" value=\"0\"></td>\n");
      out.write("\t\t\t\t\t<td><a href=\"editComputer.html\" onclick=\"\">MacBook Pro</a></td>\n");
      out.write("\t\t\t\t\t<td>2006-01-10</td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td>Apple Inc.</td>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"editMode\"><input type=\"checkbox\" name=\"cb\"\n");
      out.write("\t\t\t\t\t\tclass=\"cb\" value=\"0\"></td>\n");
      out.write("\t\t\t\t\t<td><a href=\"editComputer.html\" onclick=\"\">Connection\n");
      out.write("\t\t\t\t\t\t\tMachine</a></td>\n");
      out.write("\t\t\t\t\t<td>1987-01-01</td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td>Thinking Machines</td>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"editMode\"><input type=\"checkbox\" name=\"cb\"\n");
      out.write("\t\t\t\t\t\tclass=\"cb\" value=\"0\"></td>\n");
      out.write("\t\t\t\t\t<td><a href=\"editComputer.html\" onclick=\"\">PowerBook</a></td>\n");
      out.write("\t\t\t\t\t<td>1991-01-01</td>\n");
      out.write("\t\t\t\t\t<td>2006-01-01</td>\n");
      out.write("\t\t\t\t\t<td>Apple Inc.</td>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"editMode\"><input type=\"checkbox\" name=\"cb\"\n");
      out.write("\t\t\t\t\t\tclass=\"cb\" value=\"0\"></td>\n");
      out.write("\t\t\t\t\t<td><a href=\"editComputer.html\" onclick=\"\">Commodore 64</a></td>\n");
      out.write("\t\t\t\t\t<td>1982-08-01</td>\n");
      out.write("\t\t\t\t\t<td>1994-01-01</td>\n");
      out.write("\t\t\t\t\t<td>Commodore International</td>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"editMode\"><input type=\"checkbox\" name=\"cb\"\n");
      out.write("\t\t\t\t\t\tclass=\"cb\" value=\"0\"></td>\n");
      out.write("\t\t\t\t\t<td><a href=\"editComputer.html\" onclick=\"\">Altair 8800</a></td>\n");
      out.write("\t\t\t\t\t<td>1974-12-19</td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td>Micro Instrumentation and Telemetry Systems</td>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"editMode\"><input type=\"checkbox\" name=\"cb\"\n");
      out.write("\t\t\t\t\t\tclass=\"cb\" value=\"0\"></td>\n");
      out.write("\t\t\t\t\t<td><a href=\"editComputer.html\" onclick=\"\">Canon Cat</a></td>\n");
      out.write("\t\t\t\t\t<td>1987-01-01</td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td>Canon</td>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"editMode\"><input type=\"checkbox\" name=\"cb\"\n");
      out.write("\t\t\t\t\t\tclass=\"cb\" value=\"0\"></td>\n");
      out.write("\t\t\t\t\t<td><a href=\"editComputer.html\" onclick=\"\">Nokia 770</a></td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td>Nokia</td>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"editMode\"><input type=\"checkbox\" name=\"cb\"\n");
      out.write("\t\t\t\t\t\tclass=\"cb\" value=\"0\"></td>\n");
      out.write("\t\t\t\t\t<td><a href=\"editComputer.html\" onclick=\"\">NeXTcube</a></td>\n");
      out.write("\t\t\t\t\t<td>1988-01-01</td>\n");
      out.write("\t\t\t\t\t<td>1993-01-01</td>\n");
      out.write("\t\t\t\t\t<td>NeXT</td>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"editMode\"><input type=\"checkbox\" name=\"cb\"\n");
      out.write("\t\t\t\t\t\tclass=\"cb\" value=\"0\"></td>\n");
      out.write("\t\t\t\t\t<td><a href=\"editComputer.html\" onclick=\"\">IBM 650</a></td>\n");
      out.write("\t\t\t\t\t<td>1953-01-01</td>\n");
      out.write("\t\t\t\t\t<td>1962-01-01</td>\n");
      out.write("\t\t\t\t\t<td>IBM</td>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"editMode\"><input type=\"checkbox\" name=\"cb\"\n");
      out.write("\t\t\t\t\t\tclass=\"cb\" value=\"0\"></td>\n");
      out.write("\t\t\t\t\t<td><a href=\"editComputer.html\" onclick=\"\">PlayStation 2</a></td>\n");
      out.write("\t\t\t\t\t<td>2000-03-24</td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td>Sony</td>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"editMode\"><input type=\"checkbox\" name=\"cb\"\n");
      out.write("\t\t\t\t\t\tclass=\"cb\" value=\"0\"></td>\n");
      out.write("\t\t\t\t\t<td><a href=\"editComputer.html\" onclick=\"\">Archos 101</a></td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"editMode\"><input type=\"checkbox\" name=\"cb\"\n");
      out.write("\t\t\t\t\t\tclass=\"cb\" value=\"0\"></td>\n");
      out.write("\t\t\t\t\t<td><a href=\"editComputer.html\" onclick=\"\">Nintendo 3DS</a></td>\n");
      out.write("\t\t\t\t\t<td>2010-03-23</td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td>Nintendo</td>\n");
      out.write("\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t\t</tbody>\n");
      out.write("\t\t</table>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<table>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th>id</th>\n");
      out.write("\t\t\t<th>name</th>\n");
      out.write("\t\t\t<th>company id</th>\n");
      out.write("\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t<c:forEach items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computerList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" var=\"computer\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computer.companyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</c:forEach>\n");
      out.write("\t</table>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<footer class=\"navbar-fixed-bottom\">\n");
      out.write("\t<div class=\"container text-center\">\n");
      out.write("\t\t<ul class=\"pagination\">\n");
      out.write("\t\t\t<li><a href=\"#\" aria-label=\"Previous\"> <span\n");
      out.write("\t\t\t\t\taria-hidden=\"true\">&laquo;</span>\n");
      out.write("\t\t\t</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\">1</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\">2</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\">3</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\">4</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\">5</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\" aria-label=\"Next\"> <span aria-hidden=\"true\">&raquo;</span>\n");
      out.write("\t\t\t</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t<div class=\"btn-group btn-group-sm pull-right\" role=\"group\">\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-default\">10</button>\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-default\">50</button>\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-default\">100</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\t<script src=\"../js/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"../js/bootstrap.min.js\"></script>\n");
      out.write("\t<script src=\"../js/dashboard.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
