version: "2"

services: 
  #First images to launch is the db volume
  mysql:
    image: "mysql"
    container_name: hub-computerdb-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - "3306"
    volumes: 
      - ./sql-script:/docker-entrypoint-initdb.d
  java: 
    image: "java"
    container_name: computerdb-java
  jenkins:
    image: "jenkins"
    container_name: computerdb-jenkins
    ports:
      - 8081:8080
  maven:
    image: "maven"
    container_name: computer-maven
  tomcat:
    image: "tomcat"
    container_name: computer-tomcat
    ports:
      - 8082:8080
    volumes: 
      - ./cdb/computerdb.war:/usr/local/tomcat/webapps/CDB.war
